// Code généré automatiquement. Ne pas modifier.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "9$M0u0WMa8jR)S%YagO/":
            case "norsys1":return img`
7 7 f f f f f f f f f f f f 7 7 
7 f f f f 8 8 8 8 8 f f f f f 7 
7 f f f 8 f f f f f 8 f f f f f 
f f f f 8 f f f f f 8 f f f f f 
f f 7 7 7 7 7 f 2 2 2 2 2 f f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f f 8 8 8 8 8 f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f f 7 7 7 7 7 8 2 2 2 2 2 f f f 
f f f f 7 7 8 8 f f f f 2 f f f 
f f f f 7 8 8 f f f f 2 2 f f f 
f f f 7 7 8 f f f f 2 2 f f f f 
f f f 7 8 8 f f 2 2 2 f f f f 7 
7 7 7 7 8 2 2 2 2 f f f f f 7 7 
`;
            case "R9q{NEJjh0,]4*l5VF2-":
            case "norsys2":return img`
7 7 f f f f f f f f f f f f 7 7 
7 f f f f 8 8 8 8 8 f f f f f 7 
7 f f f 8 f f f f f 8 f f f f f 
f f f f 8 f f f f f 8 f f f f f 
f f 7 7 7 7 7 f 2 2 2 2 2 f f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f f 8 8 8 8 8 f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f f 7 7 7 7 7 8 2 2 2 2 2 f f f 
f f f f 7 7 8 8 f f f f 2 f f f 
f f f f 7 8 8 f f f f 2 2 f f f 
f f f 7 7 8 f f f f 2 2 f f f f 
f f f 7 8 8 f f 2 2 2 f f f f 7 
7 7 7 7 8 2 2 2 2 f f f f f 7 7 
`;
            case "u?7HKRdcozaPH$sSzqYM":
            case "norsys3":return img`
7 7 f f f f f f f f f f f f 7 7 
7 f f f f 8 8 8 8 8 f f f f f 7 
7 f f f 8 f f f f f 8 f f f f f 
f f f f 8 f f f f f 8 f f f f f 
f f 7 7 7 7 7 f 2 2 2 2 2 f f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f f 8 8 8 8 8 f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f f 7 7 7 7 7 8 2 2 2 2 2 f f f 
f f f f 7 7 8 8 f f f f 2 f f f 
f f f f 7 8 8 f f f f 2 2 f f f 
f f f 7 7 8 f f f f 2 2 f f f f 
f f f 7 8 8 f f 2 2 2 f f f f 7 
7 7 7 7 8 2 2 2 2 f f f f f 7 7 
`;
            case "nxUrB#1UVtSg*!)%efH}":
            case "norsys4":return img`
7 7 f f f f f f f f f f f f 7 7 
7 f f f f 8 8 8 8 8 f f f f f 7 
7 f f f 8 f f f f f 8 f f f f f 
f f f f 8 f f f f f 8 f f f f f 
f f 7 7 7 7 7 f 2 2 2 2 2 f f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f f 8 8 8 8 8 f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f f 7 7 7 7 7 8 2 2 2 2 2 f f f 
f f f f 7 7 8 8 f f f f 2 f f f 
f f f f 7 8 8 f f f f 2 2 f f f 
f f f 7 7 8 f f f f 2 2 f f f f 
f f f 7 8 8 f f 2 2 2 f f f f 7 
7 7 7 7 8 2 2 2 2 f f f f f 7 7 
`;
            case "26Mqx:,AECp5qTVPvOb}":
            case "norsys5":return img`
7 7 f f f f f f f f f f f f 7 7 
7 f f f f 8 8 8 8 8 f f f f f 7 
7 f f f 8 f f f f f 8 f f f f f 
f f f f 8 f f f f f 8 f f f f f 
f f 7 7 7 7 7 f 2 2 2 2 2 f f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f f 8 8 8 8 8 f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f f 7 7 7 7 7 8 2 2 2 2 2 f f f 
f f 7 f f f f 8 f f f f 2 f f f 
f f 7 f f f 8 f f f f 2 2 f f f 
f f 7 7 f f 8 8 f f 2 2 f f f f 
f f f 7 7 f f 8 8 f 2 f f f f 7 
f f f f 7 7 7 f 8 8 2 2 f f 7 7 
`;
            case "vfN~9ST8?P9rT^P}}mI^":
            case "norsys6":return img`
7 7 f f f f f f f f f f f f 7 7 
7 f f f f 8 8 8 8 8 f f f f f 7 
7 f f f 8 f f f f f 8 f f f f f 
f f f f 8 f f f f f 8 f f f f f 
f f 7 7 7 7 7 f 2 2 2 2 2 f f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f 8 f f 7 f f 8 f f 2 f f 
f 7 f f f 8 8 8 8 8 f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f 7 f f f f f 8 f f f f f 2 f f 
f f 7 7 7 7 7 8 2 2 2 2 2 f f f 
f f f 7 7 7 7 8 2 f f f f f f f 
7 7 7 7 8 8 8 8 2 f f f f f f f 
7 8 8 8 8 2 2 2 2 f f f f f f f 
8 8 2 2 2 2 f f f f f f f f f 7 
8 2 2 f f f f f f f f f f f 7 7 
`;
            case "image1":
            case "potaux 1 haut":return img`
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
`;
            case "image2":
            case "potaux bas 1":return img`
........................
........................
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
.....eeeeeeeeeeeee......
`;
            case "image3":
            case "haut 2":return img`
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
........................
........................
........................
`;
            case "image4":
            case "bas 2":return img`
........................
........................
........................
........................
........................
........................
........................
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
`;
            case "image5":
            case "haut 3":return img`
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
........................
........................
........................
........................
........................
........................
`;
            case "image6":
            case "bas 3":return img`
........................
........................
........................
........................
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
`;
            case "image7":
            case "haut 4":return img`
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
........................
`;
            case "image8":
            case "bas 4":return img`
........................
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Code généré automatiquement. Ne pas modifier.
